### ISSUE TITLE
Can't get a gun

### ISSUE THREAD

**Issue by humangenome** [domuk/Arma3-404Wasteland-Stratis#2]
You have to move the car to get a gun sometimes.

**Comment by Tom-Morriss** [comment]
Fixed this bug in the next update should be good now.

**Comment by humangenome** [comment]
This issue is still there. You have to move a vehicle or move a weapon/binoculars to the ground before moving to your inventory.

**Comment by ghost** [comment]
This is very likely a bug of Arma 3 not the mission. I also recoginzed that right clicking binaculars, to move them in you inventor, doesn't work. You have to drag and drop them.
